[versions]
gradle-wrapper = "8.6"
jdk-source = "21"
jdk-target = "21"
junit = "5.10.2"

[plugins]

[libraries]

junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
